language: erlang
dist: xenial
sudo: required

services:
        - docker

branches:
        only:
                - master
                - stable
                - /^rel\-\d+\.\d+$/
                - /^\d+\.\d+\.\d+([a-z0-9\-\+])*/

otp_release:
        - 20.3

matrix:
  include:
      - name: "20.3 mssql/ldap"
        script: ./tools/test-runner.sh --skip-cover-stop --docker --fast-build --verbose --retry-big-tests --jobs 3 4 --skip-auto-recompile --delay-setup-db 90
      - name: "20.3 small/mnesia/elasticsearch_cassandra"
        script: ./tools/test-runner.sh --skip-cover-stop --docker --fast-build --verbose --retry-big-tests --jobs 1 2 5 --skip-auto-recompile --delay-setup-db 90
      - name: "21.3 pgsql/mysql"
        script: ./tools/test-runner.sh --skip-cover-stop --docker --fast-build --verbose --retry-big-tests --jobs 7 8 --skip-auto-recompile --delay-setup-db 90
      - name: "21.3 small/riak"
        script: ./tools/test-runner.sh --skip-cover-stop --docker --fast-build --verbose --retry-big-tests --jobs 9 19 --skip-auto-recompile --delay-setup-db 90

      - name: "20.3 mssql/ldap"
        script: ./tools/test-runner.sh --skip-cover-stop --docker --fast-build --verbose --retry-big-tests --jobs 3 4 --skip-auto-recompile
      - name: "20.3 small/mnesia/elasticsearch_cassandra"
        script: ./tools/test-runner.sh --skip-cover-stop --docker --fast-build --verbose --retry-big-tests --jobs 1 2 5 --skip-auto-recompile
      - name: "21.3 pgsql/mysql"
        script: ./tools/test-runner.sh --skip-cover-stop --docker --fast-build --verbose --retry-big-tests --jobs 7 8 --skip-auto-recompile
      - name: "21.3 small/riak"
        script: ./tools/test-runner.sh --skip-cover-stop --docker --fast-build --verbose --retry-big-tests --jobs 9 19 --skip-auto-recompile

      - name: "20.3 mssql/ldap"
        script: ./tools/test-runner.sh --skip-cover-stop --docker --fast-build --verbose --retry-big-tests --jobs 3 4 --skip-auto-recompile
      - name: "20.3 small/mnesia/elasticsearch_cassandra"
        script: ./tools/test-runner.sh --skip-cover-stop --docker --fast-build --verbose --retry-big-tests --jobs 1 2 5 --skip-auto-recompile
      - name: "21.3 pgsql/mysql"
        script: ./tools/test-runner.sh --skip-cover-stop --docker --fast-build --verbose --retry-big-tests --jobs 7 8 --skip-auto-recompile
      - name: "21.3 small/riak"
        script: ./tools/test-runner.sh --skip-cover-stop --docker --fast-build --verbose --retry-big-tests --jobs 9 19 --skip-auto-recompile

      - name: "20.3 mssql/ldap"
        script: ./tools/test-runner.sh --skip-cover-stop --docker --fast-build --verbose --retry-big-tests --jobs 3 4 --skip-auto-recompile
      - name: "20.3 small/mnesia/elasticsearch_cassandra"
        script: ./tools/test-runner.sh --skip-cover-stop --docker --fast-build --verbose --retry-big-tests --jobs 1 2 5 --skip-auto-recompile
      - name: "21.3 pgsql/mysql"
        script: ./tools/test-runner.sh --skip-cover-stop --docker --fast-build --verbose --retry-big-tests --jobs 7 8 --skip-auto-recompile
      - name: "21.3 small/riak"
        script: ./tools/test-runner.sh --skip-cover-stop --docker --fast-build --verbose --retry-big-tests --jobs 9 19 --skip-auto-recompile

      - name: "20.3 mssql/ldap"
        script: ./tools/test-runner.sh --skip-cover-stop --docker --fast-build --verbose --retry-big-tests --jobs 3 4 --skip-auto-recompile
      - name: "20.3 small/mnesia/elasticsearch_cassandra"
        script: ./tools/test-runner.sh --skip-cover-stop --docker --fast-build --verbose --retry-big-tests --jobs 1 2 5 --skip-auto-recompile
      - name: "21.3 pgsql/mysql"
        script: ./tools/test-runner.sh --skip-cover-stop --docker --fast-build --verbose --retry-big-tests --jobs 7 8 --skip-auto-recompile
      - name: "21.3 small/riak"
        script: ./tools/test-runner.sh --skip-cover-stop --docker --fast-build --verbose --retry-big-tests --jobs 9 19 --skip-auto-recompile

notifications:
    webhooks:
        # trigger Buildtime Trend Service to parse Travis CI log
        - https://buildtimetrend.herokuapp.com/travis
        - https://tide.erlang-solutions.com/api/travis_ci/events
    on_start: always

cache:
        directories:
                - $HOME/.cache/rebar3
