language: erlang
dist: trusty
sudo: required
addons:
    apt:
        packages:
        - libpam0g-dev
        - libexpat1-dev
        - odbc-postgresql
        - slapd
        - ldap-utils
        - golang # used for google drive test results upload
        - unixodbc  # for mssql
        - tdsodbc   # for mssql
    hosts:
        # travis tries to resolve muc.localhost and fails
        # used in MUC + s2s tests combination
        - muc.localhost
before_install:
        - tools/configure $REL_CONFIG
install:
        - test -z "$FEATURES" || ./tools/unlock_disabled_deps
        - travis_retry ./rebar3 get-deps
        - ./rebar3 compile
        - make dev
        - tools/travis-build-tests.sh
        - travis_retry pip install --user codecov
before_script:
        - tools/travis-setup-db.sh
        - if [ $PRESET = 'ldap_mnesia' ]; then sudo tools/travis-setup-ldap.sh; fi
script: tools/travis-test.sh -p $PRESET

after_failure:
        - cat `ls -1 -d -t apps/ejabberd/logs/ct_run* | head -1`/apps.ejabberd.logs/run.*/suite.log
        - if [ -s _build/mim1/rel/mongooseim/log/crash.log ]; then cat _build/mim1/rel/mongooseim/log/crash.log; fi
        - if [ -s _build/mim2/rel/mongooseim/log/crash.log ]; then cat _build/mim2/rel/mongooseim/log/crash.log; fi
        - tail -100 _build/mim1/rel/mongooseim/log/ejabberd.log
        - tail -100 _build/mim2/rel/mongooseim/log/ejabberd.log

after_success:
        # env variables help to distinguish CI builds
        # It takes less time without gcov
        - codecov --disable=gcov --env PRESET
        - ./rebar3 coveralls send
        - if [ -n "${DOCKERHUB_PASS}" ] && [ $PRESET = 'internal_mnesia' ] && [ $TRAVIS_OTP_RELEASE = "19.3" ];
            then tools/travis-build-and-push-docker.sh;
          fi

after_script:
        - tools/travis-prepare-log-dir.sh
        - if [ -n "${AWS_SECRET_ACCESS_KEY}" ]; then tools/travis-upload-to-s3.sh; fi
        - if [ -n "${GDRIVE_SERVICE_ACCOUNT_CREDENTIALS}" ]; then tools/travis-upload-to-gdrive.sh; fi
        - tools/travis-secure-erase.sh /tmp/serviceAccountCredentials

services:
        - redis-server
        - docker

branches:
        only:
                - master
                - stable
                - /^rel\-\d+\.\d+$/
                - /^\d+\.\d+\.\d+([a-z0-9\-\+])*/

otp_release:
        - 19.3
env:
        # All features
        - PRESET=internal_mnesia DB=mnesia REL_CONFIG=with-all TLS_DIST=yes
        - PRESET=mysql_redis DB=mysql REL_CONFIG="with-mysql with-redis"
          FEATURES="with-all without-mysql without-odbc without-riak without-cassandra without-jingle-sip without-debugging without-syslog"
        - PRESET=odbc_mssql_mnesia DB=mssql REL_CONFIG=with-odbc
          FEATURES="with-all without-mysql without-pgsql without-riak without-cassandra without-jingle-sip without-debugging without-syslog"
        - PRESET=ldap_mnesia DB=mnesia REL_CONFIG=with-none
          FEATURES="with-all without-mysql without-odbc without-pgsql without-syslog"
        - PRESET=cassandra_mnesia DB=cassandra REL_CONFIG=with-cassandra CASSANDRA_VERSION=3.9
          FEATURES="with-all without-mysql without-pgsql without-odbc without-riak without-jingle-sip without-debugging without-syslog"
          # In case you want to test with another ODBC driver, uncomment this
      # - PRESET=odbc_pgsql_mnesia DB=pgsql REL_CONFIG=with-odbc

matrix:
    include:
        - otp_release: 20.0
          env: PRESET=dialyzer_only
        - otp_release: 20.0
          env: PRESET=pgsql_mnesia DB=pgsql REL_CONFIG="with-pgsql with-jingle-sip"
               FEATURES="with-all without-pgsql without-odbc without-riak without-cassandra without-debugging without-syslog"
        - otp_release: 18.3
          env: PRESET=riak_mnesia DB=riak REL_CONFIG=with-riak
        - otp_release: 19.3
          env: PRESET=pkg pkg_PLATFORM=centos7
        - otp_release: 19.3
          env: PRESET=pkg pkg_PLATFORM=debian_stretch

notifications:
    webhooks:
        # trigger Buildtime Trend Service to parse Travis CI log
        - https://buildtimetrend.herokuapp.com/travis
        - https://tide.erlang-solutions.com/api/travis_ci/events
    on_start: always

cache:
        directories:
                - $HOME/.cache/rebar3

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  skip_cleanup: true
  file: mongooseim-$TRAVIS_BRANCH.OTP-$TRAVIS_OTP_RELEASE.$(lsb_release -is | tr "A-Z" "a-z").$(lsb_release -rs).$(uname -m).tar.bz2
  on:
    tags: true
    condition: "$PRESET.$TRAVIS_OTP_RELEASE = internal_mnesia.18.3"
