language: erlang
dist: xenial
sudo: required

services:
        - docker
#       - redis-server

branches:
        only:
                - master
                - stable
                - /^rel\-\d+\.\d+$/
                - /^\d+\.\d+\.\d+([a-z0-9\-\+])*/

otp_release:
        - 20.3
env:
  global:
    - RUN_SMALL_TESTS=false
  matrix:


matrix:
  include:
      - otp_release: 19.3
        script: ./tools/test-runner.sh --skip-cover --docker --verbose --retry-big-tests --jobs 3 4

notifications:
    webhooks:
        # trigger Buildtime Trend Service to parse Travis CI log
        - https://buildtimetrend.herokuapp.com/travis
        - https://tide.erlang-solutions.com/api/travis_ci/events
    on_start: always

cache:
        directories:
                - $HOME/.cache/rebar3

#deploy:
#  provider: releases
#  api-key: $GITHUB_TOKEN
#  skip_cleanup: true
#  file: mongooseim-$TRAVIS_BRANCH.OTP-$TRAVIS_OTP_RELEASE.$(lsb_release -is | tr "A-Z" "a-z").$(lsb_release -rs).$(uname -m).tar.bz2
#  on:
#    tags: true
#    condition: "$PRESET.$TRAVIS_OTP_RELEASE = internal_mnesia.18.3"
