#!/usr/bin/env bash

# Bash version
function time_buffered
{
    delay=$1
    while read line; do
        printf "%d %s\n" "$(date +%s)" "$line"
    done | while read ts line; do
        now=$(date +%s)
        if (( now - ts < delay)); then
            sleep $(( now - ts ))
        fi
        printf "%s\n" "$line"
    done
}

# Try to compile
#if test ! -d _build/.test_runner/delay; then
#    mkdir -p _build/.test_runner
#    git clone "https://github.com/arcusfelis/delay.git" _build/.test_runner/delay
#    make -C _build/.test_runner/delay || echo "Failed to compile C version of delay"
#fi

SECONDS=$1

if test -f _build/.test_runner/delay/delay; then
    # 3k per second limit due to travis not working good with fast output
    _build/.test_runner/delay/delay "$SECONDS"
else
    echo "Fallback for bash version of time_buffered"
    time_buffered "$SECONDS"
fi
